version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload

jobs:
  build:
    working_directory: ~/showtunes
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: "Run test coverage"
          command: npm run coverage
      - store_artifacts:
          path: coverage
