version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    working_directory: ~/showtunes
    docker:
      - image: cimg/node:16.15-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: "Check Chrome install"
          command: |
            google-chrome --version
            chromedriver --version
      - checkout
      - restore_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: "Run unit tests and code coverage"
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: "coverage/ChromeHeadless/coverage-final.json"
