version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    working_directory: ~/showtunes
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: showtunes-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: "Run unit tests"
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: "Run test coverage"
          command: npm run coverage
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: "coverage/ChromeHeadless/coverage-final.json"
